---
- hosts: web  #group name from the inventory
  
  vars:
    pack_name: httpd
    serv_name: httpd
  
  tasks:
    - name: Install {{ pack_name }}
      yum: pkg={{ pack_name }} state=installed
      become: yes

    - name: Start {{ serv_name }}
      service: name={{ serv_name }} state=started
      become: yes
      tags:
        - start
    - name: Stop {{ serv_name }}
      service: name={{ serv_name }} state=stopped
      become: yes
      tags:
        - stop

    - name: check Content
      shell: 'cat /usr/share/httpd/noindex/index.html | grep -i "hello world" | wc -l'
      register: output_content
      become: yes

    - debug: var=output_content

    - name: Ensure SELinux is set to enforcing mode
      lineinfile:
        path: /usr/share/httpd/noindex/index.html
        regexp: 'HELLO WORLD'
        line: My Name is Pravin
      become: yes
      notify: RESTART HTTPD
      when: output_content.stdout != "0"

  handlers:
    - name: RESTART HTTPD
      service: name={{ serv_name }} state=restarted
      become: yes 
...
